nodeLinker: node-modules

npmScopes:
  danielwii:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: ${NPM_AUTH_TOKEN}
  asuna-stack:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: ${NPM_AUTH_TOKEN}

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
